export { BaseFileConnector } from './base'
export { SFTPFileConnector } from './sftp'
export { ExecFileConnector } from './exec'
export { SSHFileClient } from './ssh-file-client'
export { assertSafeLocalPath } from './path-safety'
export type { LocalPathOpts } from './path-safety'
export { FileManager, fileManager } from './manager'
export type { GetSSHConfigFn } from './manager'
export { startDownloadWorker, runDownloadWorkerAndWait, setMainWindow, cancelDownload, cancelDownloadsBySession, cleanupAllWorkers, registerTaskMeta } from './download-worker-manager'
export { startUploadWorker, runUploadWorkerAndWait, setMainWindowForUpload, cancelUpload, cancelUploadsBySession, cleanupAllUploadWorkers } from './upload-worker-manager'